# Generated by Django 4.0.5 on 2022-07-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('operation_id', models.IntegerField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('output', models.IntegerField()),
                ('output_type2', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField()),
                ('iron_floors', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='fuel_incom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('operation_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='iron_purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pricing', models.FloatField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='iron_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pricing', models.FloatField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pistons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piston', models.CharField(choices=[('piston1', 'piston1'), ('piston2', 'piston2'), ('piston3', 'piston3')], max_length=255)),
                ('date', models.DateField()),
                ('output', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='uses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='weight_gain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='money_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('income', 'income'), ('expenses', 'expenses')], max_length=255)),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('expenses_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pages.expenses')),
                ('income_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pages.income')),
            ],
        ),
        migrations.CreateModel(
            name='fuel_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('fuel', 'fuel'), ('fuel_incom', 'fuel_incom')], max_length=255)),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('fuel_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pages.fuel')),
                ('fuel_incom_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pages.fuel_incom')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='use',
            field=models.ManyToManyField(to='pages.uses'),
        ),
    ]
