# Generated by Django 4.0.5 on 2022-07-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pistons',
            name='output',
        ),
        migrations.RemoveField(
            model_name='pistons',
            name='piston',
        ),
        migrations.AddField(
            model_name='pistons',
            name='piston1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pistons',
            name='piston2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pistons',
            name='piston3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
